# OneConfig configuration file
# TODO: This config file contains quite a few explanation lines, to show the capabilities.
#       Those would be better kept in the documentatition.
project:  # Project information
    name: one-config  # can be whatever you want, but it is a good idea to give it the same
                      # name as the python package

    version: 0.1.0  # should always be given
    # add a short but meaningfull description here
    description: Collect all config information for your project in one place.

    author: &author  # The author can also be a list
        Matthias Bosewitz
    copyright: 2019, bosewitz.com
    license:  GNU General Public License (Version 3)  # always a good idea to specify a license

    website:    # you can supply one or many websites
        homepage: https://bosewitz.com/software/one-config
        github:   https://github.com/batthias/one-config

    # TODO: create logo (and an icon for atom) (not super important)
    # icon: one-config.png

tasks:  # Tasks to be completed
    - name:         generate-files  # this is the file generator
      cmd:          python -m oneconfig.generator  # the generator can be called in a folder to generate files
      description:  Generate other files from the config file.

python:  # Python settings ----------------------------------------------------------
    kernel:
        default: 3.7  # by default this package recommends using python 3.7 …
        required: >= 3.6  # … but all versions above 3.6 are fine

    importName: &importName
        oneconfig

    requirements:  # the package requirements sorterd by name
        - name:         jinja2
          description:  render templates
        - name:         pyyaml
          description:  load and save yaml files

    # dependenciesLock: !load dependencies.lock.yml  # lock some versions which worked

    style:  # what are the styles for python files
        indentation: 4 spaces  # options: "{n} spaces", "tabs", you cannot mix
        trailingCommas: all  # options: "all", "any", "none"
        typeHints: all   # require everything to have type hints
        # typeHints: any   # type hints are allowed but not enforced
        # typeHints: none  # type hints are forbidden

tests:
    testSuite:  nose.collector

generatedFiles:  # files that can be generated automatically from the config
    - file:     setup.py  # the setup.py can be easily generated
      template: python/setup-default
    - file:     requirements.txt  # the requirements.txt can of course be generated
      template: python/requirements-productive
