# Configuration file schema
# This specifies what a configuration file must look like

# I want to support the following logical things:
#            :  mandatory entry
# !optional  :  you can not define this
# !one_of    :  must be one of the things listed
# !any_of    :  can be any of the things listed or nothing
# ...        :  allow more entries

# I want to support the following data types:
# !string           :  string of characters (without linebreaks)
#                      supports `minLength`, `maxLength`
# !text             :  string with linebreaks
#                      supports `minLength`, `maxLength`
# !integer          :  integer value
#                      supports `min`, `max`
# !decimal          :  decimal value / float
#                      supports `min`, `max`, `precision`
# !list             :  list of elements
# !url              :  valid URL
# !email            :  valid E-Mail-Address
#
# All of them support `hint`, `default` and `match` as properties.
# all of them can also be optional

project:  # Project information (required field)
    name: !string
        match: [A-Za-z0-9_-]
        hint: my-project

    version: !string
        match: [0-9]\.[0-9](\.[0-9])?
        default: 1.0.0
        hint: version number
    description: !string
        minLength: 20
        hint: Insert your description here

    author: !one_of
        - !string Your Name
        - !list
          - !string Author 1
          - !optional_string Author 2
          - ...
    copyright: !string Copyright information

    website:
        Homepage:   !url URL of the homepage
        ...:        !url

tasks: !optional Tasks to be completed
